### ISSUE TITLE
v_from_z and give_dv

### ISSUE THREAD

**Issue by profxj** [linetools/linetools#330]
Integrate the two sets of methods on calculating velocities
and redshifts given one or the other.

**Comment by ntejos** [comment]
I think the main issue here is defining what kind of outputs do we want. I will split the two cases for clarity:

Case 1: Velocities from redshifts. Here, I think it is clear that most of the time we would like to have the output to be a "velocity difference", i.e. `dv` from a set of redshifts compared to others. However, it is not necessarily clear where would be the 0 velocity defined. I suggest then to have the following naming and format for the function: `dv_from_z(z, zref)`, where `zref` is the redshift reference where `dv=0` by definition.

Case 2: Redshifts from velocity differences. Here, this a bit more complicated because there can be more possibilities to play with. My personal preference is that we usually want to have "redshift differences", i.e. `dz` from velocity differences `dv` that were calculated at arbitrary redshift(s) `zref`. I suggest then the following name and format:  `dz_from_dv(dv, zref)`. Of course, another possibility is to have yet another function called `z_from_dv(dv, zref)` that returns `dz_from_dv(dv, zref) + zref`.

My suggestion is to refactor everything and have this 3 functions. I will keep the old ones but raising deprecation warnings or errors for the external users, and refactor everything within linetools. What do you think?

**Comment by ntejos** [comment]
Addressed in PR #331.
