### ISSUE TITLE
Convolving with instrument line spread functions before fitting data 

### ISSUE THREAD

**Issue by lwymarie** [linetools/linetools#463]
I really appreciate the files for line spread functions of COS and STIS. Would there be examples of how to use them? Is there a Python wrapper for VPFIT that you recommend, or a similar absorption-line fitting software? 

Tagging @ntejos @rcooke-ast , and other developers who have analyzed COS and STIS spectra.

**Comment by rcooke-ast** [comment]
[ALIS](https://github.com/rcooke-ast/ALIS) already allows you to fit data from COS and STIS. It hasn't been merged to the master branch, but I've given a simple example of how to use COS in the Issue you raised on ALIS recently. I don't think VPFIT has this functionality yet. ALIS calls linetools to do the fitting. I had originally implemented a "scaling factor", which stretches the LSF in linetools (as a fitting parameter in ALIS, but I've since removed this, because the COS LSF is fairly well defined.

**Comment by lwymarie** [comment]
Thank you! I like it that we have a python version of VPFIT. Closing as we should move the discussion to ALIS.
